sudo useradd -m gs_deploy
mkdir -p /home/gs_deploy/.ssh
touch /home/gs_deploy/.ssh/authorized_keys
echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCQubMJjNGRWnlD1eFyEyWKM/+FNJulNTd6IXe3HSTIs09twtw2+5OLwumr6nsPDwTRq1THTAxApArARTDs5r5f+aVvdgCXHXxB3djH7zKCcjvmFumIYOgdo6cKBLTPwIPw2UVIAJQDEybhL/49dI/DO5AaPn2v7DSlzwGFm8ywIMhprl2CvL5oZhunktNLvmpCb2vx7PHmnkBB5PvtdT1Fk9dQXklMDWE6wrEYnqnIKBIAJvwOIEb+f1jSkjQsHZVdGC8f5BYsBBCz/+XFeg6Pk/2ZwjQgavLrDLVihztQUPEogRUd62k9JVel/otNIqpA5KKBukONlB1oTobLkh//QHynh2mCXDmg0U0NO0a+8370QXuZ08oAxG9TQWY4gTIn4D0oAdBVNsvXsqhsRJfko9pNBCOQX6HMalmH+I/+CoLMd2AhELG6zIM8133xiBF3wj0+f9sfLlzwIih7thS5fUA5NEoeMMUsThNcjAqJdP1//WbFIg0LrGORn3RzVk= hotgame_gs_deploy' >> /home/gs_deploy/.ssh/authorized_keys
chown -R gs_deploy:gs_deploy /home/gs_deploy/.ssh
chmod 755 /home/gs_deploy/.ssh
chmod 644 /home/gs_deploy/.ssh/authorized_keys