version: '1.0'
name: xsw-test
displayName: xsw-test
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-21e2e804
    displayName: test_pubshell
    strategy: naturally
    trigger: auto
    executor:
      - sunnybug
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        script:
          - bash pubshell.sh
        notify:
          - certificate: xx
            events:
              - fail
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: dingtalk
        strategy:
          retry: '0'
