version: '1.0'
name: pipeline-20241024
displayName: pipeline-20241024
triggers:
  trigger: manual
stages:
  - name: stage-5724e6b3
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@php
        name: build_php
        displayName: PHP 构建
        phpVersion: '8.0'
        commands:
          - '# 设置全局composer依赖仓库地址'
          - composer config -g secure-http false
          - composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/
          - composer install
          - php -v
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches: []
        notify: []
        strategy:
          retry: '0'
