services:
  jenkins_slave:
    image: ${image_ver}
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    environment:
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_SECRET=${JENKINS_SECRET}
      - JENKINS_NAME=${JENKINS_NAME}
      - JENKINS_WORKDIR=${JENKINS_WORKDIR}
    volumes:
      - /data/jenkins-module_slave:/home/jenkins
      - /run/user/${UID}/docker.sock:/var/run/docker.sock
      - ~/bin/docker:/usr/bin/docker
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${DOCKER_HOME}:/root
      - ${AUTHORIZED_KEYS}:/root/.ssh/authorized_keys
    restart: always
    tty: true
    stdin_open: true
    command: /bin/zsh
    network_mode: bridge